name: Aikido

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
  workflow_dispatch:

jobs:
  aikido:
    uses: ricardotondello/shared-workflows/.github/workflows/aikido.yml@main
    secrets:
      inherit