name: SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  sonar-cloud:
    uses: ricardotondello/shared-workflows/.github/workflows/code_quality.yml@main
    secrets:
      inherit