name: .NET

on:
  push:
    branches: 
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build-and-tests:
    uses: ricardotondello/shared-workflows/.github/workflows/dotnet.yml@main
    secrets:
        inherit