name: Git Leaks

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
    
  workflow_dispatch:

jobs:
  gitleaks-scan:
    uses: ricardotondello/shared-workflows/.github/workflows/gitleaks.yml@main
    secrets:
        inherit