name: SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  sonar-cloud:
    uses: ricardotondello/shared-workflows/.github/workflows/sonarcloud.yml@main
    with:
      test_file_path: tests/Functional.Toolkit.OptionType.Tests/bin/Debug/net10.0
    secrets:
      inherit